app = "si-ukur"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  image = "php:8.2-fpm"

[env]
  APP_ENV = "production"
  APP_DEBUG = "false"
  APP_URL = "https://si-ukur.infinityfree.me"
  LOG_CHANNEL = "stack"
  LOG_LEVEL = "debug"

  DB_CONNECTION = "mysql"
  DB_PORT = "3306"

[deploy]
  release_command = "php artisan migrate --force"

[[services]]
  internal_port = 9000
  protocol = "tcp"

  [[services.ports]]
    port = 80

  [[services.ports]]
    port = 443

  [services.concurrency]
    type = "connections"
    soft_limit = 20
    hard_limit = 25

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "10s"
    restart_limit = 0
